[package]
name = "rsime"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
rime-api = "0.12.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "3"

[patch.crates-io]
librime-sys = { path = "./third_party/librime-rs/librime-sys" }
rime-api = { path = "./third_party/librime-rs" }
